### ISSUE TITLE
Phone starts playing music out loud after break/work notification

### ISSUE THREAD

**Issue by Alex74743** [goodtime-productivity/Goodtime#76] opened 2017-04-24 17:59 UTC
While listening to music through headphones , when the app notifies the start of a work/break session, the music being played starts being played through headphones and speakers. Music app used is Google Play Music. The same problem doesn't exist when using Bluetooth headphones. It's possible this may be similar to a duplicate issue however it's not just the notification sound that starts playing but the music as well (at least until I pause then play the music again), I would be very grateful if this bug gets fixed.
Great work with the rest of the app, it helps me a lot.

**Comment by adrcotfas** [comment] 2018-12-20 13:47
Duplicate of #25

**Closed by adrcotfas** 2018-12-20 13:47 UTC
